# Sample workflow for building and deploying a Jekyll site to GitHub Pages
name: Deploy Jekyll Site

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1 # Adjust Ruby version as needed
          bundler-cache: true

      - name: Install Jekyll and Dependencies
        run: |
          gem install jekyll bundler
          bundle install

      - name: Build Jekyll Site
        run: bundle exec jekyll build --destination _site

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: jekyll-site-artifact
          path: ./_site

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: jekyll-site-artifact

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
